In [2]:
import tensorflow as tf
print(f'TensorFlow Version: {tf.__version__}')

TensorFlow Version: 2.10.0


In [16]:
import matplotlib.pyplot as plt

In [30]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [42]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [43]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.12795542, -0.02228835,  0.06613736,  0.02009719, -0.4635584 ,
         0.45420983,  1.17464   , -0.13913853, -0.04096174, -0.29342   ]],
      dtype=float32)

In [44]:
tf.nn.softmax(predictions).numpy()

array([[0.09300527, 0.08003087, 0.08742996, 0.08349593, 0.05147737,
        0.12888372, 0.26489693, 0.07120494, 0.07855029, 0.06102483]],
      dtype=float32)

In [45]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [46]:
loss_fn(y_train[:1], predictions).numpy()

2.0488448

In [47]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [48]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3030 - accuracy: 0.9114
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1469 - accuracy: 0.9556
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1090 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0879 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0750 - accuracy: 0.9766


In [49]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0745 - accuracy: 0.9768 - 538ms/epoch - 2ms/step


[0.0745222344994545, 0.9768000245094299]

In [50]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [53]:
probability_model.compile(optimizer='Adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics=['accuracy'])

In [54]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.22208471e-07, 1.33317259e-08, 4.65123121e-05, 5.27187804e-05,
        7.20105746e-12, 1.23087602e-07, 2.66590470e-15, 9.99895453e-01,
        1.33453261e-06, 2.99988483e-06],
       [2.12272039e-06, 9.44095882e-06, 9.99980569e-01, 7.57561929e-06,
        3.91358669e-18, 1.86650581e-07, 7.03636189e-08, 2.84950693e-14,
        1.80963262e-08, 1.53879698e-12],
       [3.71848756e-08, 9.99718606e-01, 2.58445252e-05, 1.74662534e-06,
        5.86226633e-06, 5.57588100e-06, 9.18043133e-06, 1.65775025e-04,
        6.49549111e-05, 2.33039236e-06],
       [9.99810636e-01, 5.38859291e-10, 1.03108272e-04, 1.05025585e-07,
        3.01085756e-09, 4.92902018e-07, 3.07853202e-06, 7.18731389e-05,
        1.56860249e-08, 1.06957514e-05],
       [5.23355357e-06, 1.21533217e-09, 6.42762097e-06, 1.48553916e-08,
        9.97281313e-01, 3.00688644e-05, 4.88957558e-05, 5.75423124e-04,
        6.59061413e-07, 2.05203565e-03]], dtype=float32)>

In [55]:
probability_model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0745 - accuracy: 0.9768 - 688ms/epoch - 2ms/step


[0.0745222344994545, 0.9768000245094299]